export const MALAYSIA_STATES = [
  "Johor",
  "Kedah",
  "Kelantan",
  "Melaka",
  "Negeri Sembilan",
  "Pahang",
  "Perak",
  "Perlis",
  "Pulau Pinang",
  "Sabah",
  "Sarawak",
  "Selangor",
  "Terengganu",
  "Kuala Lumpur",
  "Labuan",
  "Putrajaya",
] as const;

export const CITIES_BY_STATE: Record<string, string[]> = {
  "Kuala Lumpur": [
    "Mont Kiara",
    "KLCC",
    "Bukit Bintang",
    "Chow Kit",
    "Bangsar",
    "Damansara",
    "Sri Petaling",
    "Kepong",
    "Wangsa Maju",
    "Titiwangsa",
    "Segambut",
    "Setapak",
    "Cheras",
    "Salak South",
    "Ampang",
  ],
  Selangor: [
    "Petaling Jaya",
    "Shah Alam",
    "Subang Jaya",
    "Klang",
    "Ampang",
    "Puchong",
    "Kajang",
    "Sepang",
    "Rawang",
    "Hulu Langat",
    "Cyberjaya",
    "Putrajaya",
    "Ara Damansara",
    "Bangi",
    "Semenyih",
    "Batu Caves",
  ],
  Johor: [
    "Johor Bahru",
    "Iskandar Puteri",
    "Batu Pahat",
    "Muar",
    "Kluang",
    "Segamat",
    "Pontian",
    "Kota Tinggi",
    "Pasir Gudang",
    "Kulai",
  ],
  "Pulau Pinang": [
    "Georgetown",
    "Bayan Lepas",
    "Butterworth",
    "Bukit Mertajam",
    "Nibong Tebal",
    "Tanjung Bungah",
    "Batu Ferringhi",
    "Kepala Batas",
  ],
  Perak: ["Ipoh", "Taiping", "Teluk Intan", "Manjung", "Kuala Kangsar", "Kampar", "Sitiawan"],
  Kedah: ["Alor Setar", "Sungai Petani", "Kulim", "Langkawi", "Baling", "Pendang"],
  Kelantan: ["Kota Bharu", "Pasir Mas", "Tanah Merah", "Machang", "Kuala Krai"],
  Melaka: ["Melaka City", "Ayer Keroh", "Merlimau", "Jasin", "Alor Gajah"],
  "Negeri Sembilan": ["Seremban", "Nilai", "Port Dickson", "Rembau", "Tampin"],
  Pahang: ["Kuantan", "Temerloh", "Bentong", "Raub", "Cameron Highlands"],
  Perlis: ["Kangar", "Arau", "Padang Besar"],
  Sabah: ["Kota Kinabalu", "Sandakan", "Tawau", "Lahad Datu", "Keningau"],
  Sarawak: ["Kuching", "Miri", "Sibu", "Bintulu", "Limbang"],
  Terengganu: ["Kuala Terengganu", "Kemaman", "Dungun", "Marang", "Hulu Terengganu"],
  Labuan: ["Labuan Town"],
  Putrajaya: ["Putrajaya"],
};

export const KEY_FEATURES = [
  "Private Pool",
  "Gym / Fitness Room",
  "Garden",
  "Smart Home",
  "Corner Unit",
  "High Floor",
  "End Lot",
  "Gated & Guarded",
  "CCTV",
  "Balcony",
  "Jacuzzi",
  "Sky Deck",
  "BBQ Area",
  "Co-working Space",
  "EV Charging",
  "Solar Panels",
  "Sea View",
  "City View",
  "Forest View",
  "Near LRT/MRT",
  "Near School",
  "Near Hospital",
  "Near Shopping Mall",
  "Infinity Pool",
  "Rooftop",
  "Storage Room",
  "Maid's Room",
  "Private Lift",
  "Air Conditioning",
] as const;

export const PROPERTY_TYPES = [
  { value: "apartment", label: "Apartment" },
  { value: "condo", label: "Condominium" },
  { value: "terrace", label: "Terrace House" },
  { value: "semi_d", label: "Semi-Detached (Semi-D)" },
  { value: "bungalow", label: "Bungalow" },
  { value: "commercial", label: "Commercial Property" },
  { value: "land", label: "Land" },
] as const;
